export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'Markdown'
export const GITHUB_URL = 'https://github.com/tylernix'
export const LINKEDIN_URL = 'https://linkedin.com/in/tylernix'
export const TWITTER_URL = 'https://twitter.com/tnix'
export const EMAIL_URL = 'mailto:tylernix@pm.me'