import React from 'react';
import Container from '../components/container'
import Layout from '../components/layout'
import Header from '../components/header'
import EmailSignupAuth0 from "../components/subscribe-auth0"
import SectionSeperator from "../components/section-separator"
import UnderlinedLink from '../components/underlined-link'
import Head from 'next/head'
import useUser from '../lib/hooks'

export default function Profile() {
  const { user, error } = useUser();

  if (error) return <div>{error.message}</div>;

  return (
    <>
      <Layout>
        <Head>
          <title>Profile</title>
        </Head>
          <Header />
          <Container>
            <div className="">
              {user ? (
                <div>
                  <h1 className="md:flex text-4xl md:text-6xl lg:text-7xl tracking-tighter leading-tight text-prussian-blue">
                    Your Profile
                  </h1>
                  <p className="text-sm md:text-base lg:text-xl text-prussian-blue md:max-w-4xl mb-4">
                    If you want to view what your <b>id_token</b> says about you, you can copy and paste your token into <UnderlinedLink href="https://jwt.io" text="jwt.io" target="_blank" /> to view. 
                    The <b>access_token</b> doesn't work the same since it isn't technically a "formal" <UnderlinedLink href="https://auth0.com/docs/tokens/json-web-tokens" text="Json Web Token (JWT)" target="_blank" />. It is a unique JWT generated by Auth0 (the identity provider I use) only useful to Auth0. 
                  </p>
                  <SectionSeperator />
                  <code className="block whitespace-pre overflow-x-scroll">{JSON.stringify(user, null,2)}</code>
                </div>
              ) : (
                <div>
                  <h1 className="md:flex text-4xl md:text-6xl lg:text-7xl tracking-tighter leading-tight text-prussian-blue">
                    Your session
                  </h1>
                  <p className="font-bold text-sm md:text-base lg:text-xl text-prussian-blue md:max-w-4xl mb-4">Your are not currently logged in to see your session details, but you can signup below.</p>
                  <SectionSeperator />
                  <EmailSignupAuth0 funFactText="This also signs you up for my email newsletter, just so you are aware."/>
                </div>
              )}
            </div>
                 
          </Container>
      </Layout>
    </>
  )
}
